spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financial01?characterEncoding=utf-8&useSSL=false
    username: 123
    password: 123
  application:
    name: database_service

#   热更新
  devtools:
    livereload:
      enabled: false
  autoconfigure:
    exclude:
            - org.apache.dubbo.spring.boot.autoconfigure.DubboAutoConfiguration

#  缓存类型
  cache:
    type: redis
  # redis配置信息
  redis:
    host: 192.168.198.131
    port: 6378
    password: 123456
    database: 0 #数据库索引，默认为0
    lettuce:
      pool:
        #  all is default
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml



dubbo:
  scan:
   #开启包扫描，可替代 @EnableDubbo 注解
    base-packages: com.rick.financial_dataService.serviceImpl
  # 服务名称
  application:
    name: financial_databaseService
    #注册中心的协议和地址
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.198.131:2181
    #超时时间
    timeout: 10000
  config-center:
    timeout: 10000
    #通信规则（通信协议和接口）
  protocol:
    name: dubbo
    port: 20880
    #连接监控中心
  monitor:
    protocol: registry
  #日志
logging:
  level:
    com.rick.financial_dataService: info


financial:
  pwdSalt: 6d3fa26ee93e491079a75f3cf630d135





