
#dubbo\u914D\u7F6E
dubbo:
  # \u670D\u52A1\u540D\u79F0
  application:
    name: financial_web
    #\u6CE8\u518C\u4E2D\u5FC3\u7684\u534F\u8BAE\u548C\u5730\u5740
  registry:
    protocol: zookeeper
    address: zookeeper://192.168.198.131:2181
    #\u8D85\u65F6\u65F6\u95F4
    timeout: 10000
  config-center:
    timeout: 10000
    #\u901A\u4FE1\u89C4\u5219\uFF08\u901A\u4FE1\u534F\u8BAE\u548C\u63A5\u53E3\uFF09
  protocol:
    name: dubbo
    port: 20880
    #\u8FDE\u63A5\u76D1\u63A7\u4E2D\u5FC3
  monitor:
    protocol: registry


spring:
  application:
    name: financial_task
